### ISSUE TITLE
Chars not extracted properly for Hindi

### ISSUE THREAD

**Issue by orling** [mathiasbynens/String.prototype.at#3]
I'm trying to wrap each character from an arbitrary text in a <span> element. The algorithm works fine for Western European and Cyrillic languages, Chinese and Arabic, but for Hindi at.js seems to treat the accents (or whatever they are called) as separate chars. Here's the Hindi text I'm testing with: 

अनुच्छेद 1 — सभी मनुष्यों को गौरव और अधिकारों के विषय में जन्मजात स्वतन्त्रता और समानता प्राप्त हैं। उन्हें बुद्धि और अन्तरात्मा की देन प्राप्त है और परस्पर उन्हें भाईचारे के भाव से बर्ताव करना चाहिए।

and the span-generating algotithm:

html+="<div class='line' data-index='"+lineIndex+"'>";
var char; 
var i = 0;
do{
	char = line.contents.at(i); 
	html += "<span class='char'>"+htmlEncode(char)+"</span>";
	i+=char.length;//char.length is always 1, for all languages tested
}
while(char != "");
html+="</div>";

**Comment by orling** [comment]
After some more research, Hindi can have diactric markings on its vowels that are normally rendered as part of the letter, similar to the German "ä" umlauts. Those diactrics seems to be a surogate half that stays after the letter itself, but for some reason both String.charAt and at.js report them as two separate characters. So if I want to render Hindi text letter-by-letter the diactrics result in extra chars

**Comment by mathiasbynens** [comment]
Those are combining marks — see https://mathiasbynens.be/notes/javascript-unicode#accounting-for-lookalikes for some background. `String.prototype.at` is designed to act on code points, not graphemes (just like all ES6 `String.prototype` methods).
